language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
script: 
  - ruby path_to_enlightenment.rb
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
  include:
    - { rvm: jruby-head, jdk: openjdk6 }
    - { rvm: jruby-head, jdk: openjdk7 }
    - { rvm: jruby-head, jdk: oraclejdk6 }
    - { rvm: jruby-19mode, jdk: openjdk6 }
    - { rvm: jruby-19mode, jdk: openjdk7 }
    - { rvm: jruby-19mode, jdk: oraclejdk6 }
